<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductListSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('product_lists')->insert([
            [
                'title' => "Bluetooth Wireless Headphones",
                'price' => "199.99",
                'special_price' => "149.99",
                'image' => "bluetooth_wireless_headphones.jpg",
                'category' => "Electronics",
                'subcategory' => "Audio",
                'remark' => "Best Seller",
                'brand' => "SoundPeak",
                'star' => "4.7",
                'product_code' => "SPBTH2024",
             ],
              [
                'title' => "Ergonomic Office Chair",
                'price' => "249.99",
                'special_price' => "199.99",
                'image' => "ergonomic_office_chair.jpg",
                'category' => "Furniture",
                'subcategory' => "Office Furniture",
                'remark' => "Limited Offer",
                'brand' => "ComfySit",
                'star' => "4.3",
                'product_code' => "CSOFC2024",
             ],
              [
                'title' => "Stainless Steel Refrigerator",
                'price' => "1200.99",
                'special_price' => "1100.99",
                'image' => "stainless_steel_refrigerator.jpg",
                'category' => "Appliances",
                'subcategory' => "Refrigerators",
                'remark' => "Energy Efficient",
                'brand' => "CoolTech",
                'star' => "4.6",
                'product_code' => "CTRFR2024",
             ],
              [
                'title' => "Professional Gaming Laptop",
                'price' => "1499.99",
                'special_price' => "1399.99",
                'image' => "professional_gaming_laptop.jpg",
                'category' => "Electronics",
                'subcategory' => "Computers",
                'remark' => "Top Performance",
                'brand' => "GameMaster",
                'star' => "4.8",
                'product_code' => "GMLTP2024",
             ],
              [
                'title' => "Electric Stand Mixer",
                'price' => "399.99",
                'special_price' => "349.99",
                'image' => "electric_stand_mixer.jpg",
                'category' => "Kitchenware",
                'subcategory' => "Appliances",
                'remark' => "Customer Favorite",
                'brand' => "MixWell",
                'star' => "4.4",
                'product_code' => "MWMXR2024",
             ],
              [
                'title' => "LED Desk Lamp",
                'price' => "49.99",
                'special_price' => "39.99",
                'image' => "led_desk_lamp.jpg",
                'category' => "Home Decor",
                'subcategory' => "Lighting",
                'remark' => "Eco-Friendly",
                'brand' => "BrightLite",
                'star' => "4.2",
                'product_code' => "BLDLP2024",
             ],
              [
                'title' => "Cordless Drill Set",
                'price' => "129.99",
                'special_price' => "109.99",
                'image' => "cordless_drill_set.jpg",
                'category' => "Tools",
                'subcategory' => "Power Tools",
                'remark' => "Heavy Duty",
                'brand' => "DrillMaster",
                'star' => "4.7",
                'product_code' => "DMDRL2024",
             ],
              [
                'title' => "Men's Running Shoes",
                'price' => "99.99",
                'special_price' => "79.99",
                'image' => "mens_running_shoes.jpg",
                'category' => "Apparel",
                'subcategory' => "Footwear",
                'remark' => "New Collection",
                'brand' => "FastTrack",
                'star' => "4.0",
                'product_code' => "FTSHO2024",
             ],
              [
                 'title' => "Compact Juicer Machine",
                 'price' => "89.99",
                 'special_price' => "69.99",
                 'image' => "compact_juicer_machine.jpg",
                 'category' => "Kitchenware",
                 'subcategory' => "Appliances",
                 'remark' => "Easy to Use",
                 'brand' => "JuicePro",
                 'star' => "4.1",
                 'product_code' => "JPJCM2024",
             ],
              [
                 'title' => "Waterproof Smartwatch",
                 'price' => "299.99",
                 'special_price' => "249.99",
                 'image' => "waterproof_smartwatch.jpg",
                 'category' => "Electronics",
                 'subcategory' => "Wearable Technology",
                 'remark' => "Feature-Rich",
                 'brand' => "TimeTech",
                 'star' => "4.6",
                 'product_code' => "TTWSW2024",
             ],
              [
                 'title' => "Wireless Bluetooth Speaker",
                 'price' => "59.99",
                 'special_price' => "49.99",
                 'image' => "wireless_bluetooth_speaker.jpg",
                 'category' => "Electronics",
                 'subcategory' => "Audio",
                 'remark' => "Portable",
                 'brand' => "AudioWave",
                 'star' => "4.7",
                 'product_code' => "AWSBS2024",
             ],
              [
                 'title' => "Silicone Baking Mat Set",
                 'price' => "24.99",
                 'special_price' => "19.99",
                 'image' => "silicone_baking_mat_set.jpg",
                 'category' => "Kitchenware",
                 'subcategory' => "Bakeware",
                 'remark' => "Non-Stick",
                 'brand' => "BakeEase",
                 'star' => "4.5",
                 'product_code' => "BEMBS2024",
             ],
              [
                 'title' => "Adjustable Dumbbell Set",
                 'price' => "129.99",
                 'special_price' => "99.99",
                 'image' => "adjustable_dumbbell_set.jpg",
                 'category' => "Fitness",
                 'subcategory' => "Weight Training",
                 'remark' => "Space Saver",
                 'brand' => "StrongLift",
                 'star' => "4.8",
                 'product_code' => "SLDUM2024",
             ],
              [
                 'title' => "Organic Green Tea",
                 'price' => "14.99",
                 'special_price' => "11.99",
                 'image' => "organic_green_tea.jpg",
                 'category' => "Groceries",
                 'subcategory' => "Beverages",
                 'remark' => "Health Benefits",
                 'brand' => "NatureSip",
                 'star' => "4.4",
                 'product_code' => "NSGRT2024",
             ],
              [
                 'title' => "Multi-Purpose Tool Kit",
                 'price' => "49.99",
                 'special_price' => "39.99",
                 'image' => "multi_purpose_tool_kit.jpg",
                 'category' => "Tools",
                 'subcategory' => "Hand Tools",
                 'remark' => "Versatile",
                 'brand' => "ToolMaster",
                 'star' => "4.6",
                 'product_code' => "TMTK2024",
             ],
              [
                 'title' => "Yoga Mat",
                 'price' => "29.99",
                 'special_price' => "24.99",
                 'image' => "yoga_mat.jpg",
                 'category' => "Fitness",
                 'subcategory' => "Yoga",
                 'remark' => "Eco Friendly",
                 'brand' => "ZenSpace",
                 'star' => "4.7",
                 'product_code' => "ZSYM2024",
             ],
              [
                 'title' => "Thermal Insulated Backpack",
                 'price' => "59.99",
                 'special_price' => "49.99",
                 'image' => "thermal_insulated_backpack.jpg",
                 'category' => "Outdoor",
                 'subcategory' => "Camping Gear",
                 'remark' => "Keeps Food Fresh",
                 'brand' => "OutdoorPro",
                 'star' => "4.5",
                 'product_code' => "OPBKP2024",
             ],
              [
                 'title' => "Electric Toothbrush",
                 'price' => "79.99",
                 'special_price' => "59.99",
                 'image' => "electric_toothbrush.jpg",
                 'category' => "Personal Care",
                 'subcategory' => "Dental Care",
                 'remark' => "Advanced Cleaning",
                 'brand' => "CleanSmile",
                 'star' => "4.8",
                 'product_code' => "CSTBR2024",
             ],
              [
                 'title' => "Indoor Herb Garden Kit",
                 'price' => "34.99",
                 'special_price' => "29.99",
                 'image' => "indoor_herb_garden_kit.jpg",
                 'category' => "Home & Garden",
                 'subcategory' => "Gardening",
                 'remark' => "Grow Your Own",
                 'brand' => "GreenThumb",
                 'star' => "4.3",
                 'product_code' => "GTHGK2024",
             ]
        ]);
    }
}
